openai/miniF2F

lean/src/valid/mathd_numbertheory_64.lean

cc @dwrensha (keeping your original proof around)

[mathd_numbertheory_64] keep alternative proof

---

README.md
lean/src/test/algebra_sqineq_unitcircatbpabsamblt1.lean
metamath/test/algebra-sqineq-unitcircatbpabsamblt1.mm

cc @DyeKuu 
(still need to add the Metamath version)

Add algebra_sqineq_unitcircatbpabsamblt1

---

lean/src/test/mathd_algebra_289.lean

Fixes h₂ and h₃ which are false if subtraction operates on ℕ.
cc @DyeKuu

[lean] fix mathd_algebra_289

---

metamath/test/mathd-numbertheory-233.mm
metamath/test/mathd-numbertheory-321.mm
metamath/valid/mathd-numbertheory-232.mm
metamath/valid/mathd-numbertheory-668.mm

- rewrites statements in a more algebraic way.

[Metamath] Rewrite statements

---

lean/src/test/algebra_ineq_nto1onlt2m1on.lean
lean/src/test/amc12_2001_p21.lean
lean/src/test/amc12a_2020_p7.lean
lean/src/test/amc12a_2021_p3.lean
lean/src/test/amc12b_2020_p6.lean
lean/src/test/mathd_algebra_125.lean
lean/src/test/mathd_algebra_158.lean
lean/src/test/mathd_algebra_392.lean
lean/src/valid/amc12b_2002_p3.lean
lean/src/valid/induction_divisibility_9div10tonm1.lean
lean/src/valid/induction_sum2kp1npqsqm1.lean
lean/src/valid/mathd_algebra_144.lean
lean/src/valid/mathd_algebra_69.lean
lean/src/valid/mathd_numbertheory_13.lean
lean/src/valid/mathd_numbertheory_211.lean
lean/src/valid/mathd_numbertheory_326.lean
lean/src/valid/mathd_numbertheory_42.lean

[Lean] Fix natural type

---

lean/src/test/aime_1983_p1.lean
lean/src/test/aime_1994_p3.lean
lean/src/test/aime_1995_p7.lean
metamath/test/aime-1983-p1.mm
metamath/test/aime-1994-p3.mm
metamath/test/aime-1995-p7.mm

Just some practice problems from a while back.

Kudzo test

---

lean/src/valid/algebra_amgm_faxinrrp2msqrt2geq2mxm1div2x.lean
lean/src/valid/imo_1990_p3.lean
lean/src/valid/induction_divisibility_3div2tooddnp1.lean
lean/src/valid/induction_divisibility_3divnto3m2n.lean
leanpkg.toml

bump mathlib

---

lean/src/test/induction_1pxpownlt1pnx.lean
metamath/test/induction-1pxpownlt1pnx.mm

[Lean & Metamath] fix statement

---

README.md

Updated README + Cut of v1

---

README.md

README: add preprint bibtex

---

lean/src/test.lean

Add in the proof.
Thanks to Alex J Best and anyone who helped me on zulip.

Numbertheory 4x3m7y3neq2003

---

lean/src/test.lean

Thanks to Patrick Johnson and Mario Carneiro for helping me simply the proof.

complete induction_nfactltnexpnm1ngt3

---

lean/src/test.lean

Thanks to discussion with Kevin Buzzard and Damiano Testa for helping me simplify my proof

add proof of induction_12dvd4expnp1p20

---

lean/src/minif2f_import.lean
lean/src/test.lean
lean/src/valid.lean
leanpkg.toml

Bump mathlib to 30a731ca565b92955e40274652f4c2b6f4db79f4

---

lean/src/test.lean

Thanks to spolu for the bump, that let me complete this proof!

prove: ∃ a b, irrational a ∧ irrational b ∧ ¬ irrational (a^b)

---

lean/src/minif2f_import.lean
lean/src/test.lean

I had to add the import:
```
import analysis.special_functions.logb
```
to the imports file, I hope that's ok.

prove mathd_algebra_484

---

lean/src/test.lean

I think there were was a problem with this statement, because after knocking of the square root, I was finally able to solve it, additionally it seems to hold for all real numbers as well, so I generalized it to that (let me know if that's alright).

complete mathd_algebra_141

---

lean/src/valid.lean

cc @DyeKuu 
cc @dselsam will propagate manually to mathzoo

fix: amc12a_2017_p7

---

hollight/valid/mathd-algebra-185.ml
lean/src/valid.lean

Resolves #73 
lean, hol light: fixed in this PR
metamath: looks good
cc @javier-m

Fix mathd_algebra_185

---

hollight/valid/mathd-numbertheory-301.ml
lean/src/valid.lean

Resolves #86 
- lean, hol light: fix mathd-numbertheory-301, cc @javier-m

Fix #86 & Add lean proof

---

lean/src/test.lean

Resolves #85 
- lean: fix & add proof
- metamath: looks good

Fix #85 & Add lean proof

---

hollight/test/mathd-numbertheory-227.ml
lean/src/test.lean

Resolves #81 
- lean, hol light: adds constraints that `x y n` cannot be 0, cc @javier-m 
- metamath: looks good

Fix #81 & Add lean proof

---

isabelle/valid/aime_1990_p2.thy
isabelle/valid/numbertheory_sumkmulnckeqnmul2pownm1.thy

For some reason the two valid files didn't get committed... my apologies
With these two files committed, we have 244 valid theories and 244 test theories.

two valid files didn't get commited

---

isabelle/test/mathd_algebra_440.thy
isabelle/test/mathd_algebra_441.thy
isabelle/test/mathd_numbertheory_227.thy
isabelle/test/numbertheory_3pow2pownm1mod2pownp3eq2pownp2.thy

I resolved the last few TODOs in the miniF2F/Isabelle, which should now be ready for benchmarking.

resolved the TODOs corresponding to the issues I raised

---

lean/src/test.lean

Replaced ℕ+ by ℕ, set differences by finset.Icc, and fixed some mistakes.

Fix test.lean

---

lean/src/test.lean
lean/src/valid.lean

Changed ℕ+ into ℕ, finset.range into finset.Icc, used real.logb and fixed some mistakes

Fix valid.lean
